name: 直播源自动更新
on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC时间3点运行
  workflow_dispatch:      # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: pip install requests
      
      - name: 执行处理脚本
        run: python scripts/processor.py
      
      - name: 提交变更
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/live_sources.txt
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M')"
          git push
